server:
  context-path: /tmall_springboot
  port: 8080

spring:
  #database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tmall_springboot?characterEncoding=UTF-8
    username: root
    password: admin

  #设置上传文件大小，默认只有1 m
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

  #设置jpa
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #显示 hibernate运行的 sql 语句
    show-sql: true

  #设置thymeleaf
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5

  #设置redis
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最小空闲连接
      min-idle: 0
    #连接超时时间（毫秒）
    timeout: 0

  #设置ElasticSearch的port
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300